### ISSUE TITLE
Missing heading hierarchy classes

### ISSUE THREAD

**Issue by danielmatthew** [talis/bootstrap-sass#11]
```css
h1, h2, h3, h4, h5, h6,
.h1, .h2, .h3, .h4, .h5, .h6 {
  font-family: $headings-font-family;
  font-weight: $headings-font-weight;
  line-height: $headings-line-height;
}
```

Bollocks.
