### ISSUE TITLE
Add "blank-slate" styles and example

### ISSUE THREAD

**Issue by danielmatthew** [talis/bootstrap-sass#40]
Currently the only example of this outside of projects sits on design.talis.com

```html
<section class="list-state-grey list-state--empty">
  <header class="list-state-grey__hero-icon">
    <i class="fa fa-fw fa-key hero-icon" aria-hidden="true"></i>
    <h3>Authenticate</h3>
    <p>We just need to check your credentials before we send you on your way.</p>
    <button class="btn btn-primary">Click to continue</button>
  </header>
</section>
```

```css
.list-state-grey {
  padding: 5rem;

  color: #5e5e5e;
  text-align: center;

  background-color: #f2f2f2;
}

  .list-state-grey__hero-icon > .fa {
    display: block;
    width: 12rem;
    height: 12rem;
    margin: 0 auto 2rem;

    font-size: 6rem;
    line-height: 12rem;
    color: #5e5e5e;

    background-color: #fff;
    border-radius: 12rem;
  }
```

These should be added as a new component to the demo page visible at http://talis.github.io/bootstrap-sass
