### ISSUE TITLE
Remove box-shadow from action button in active state

### ISSUE THREAD

**Issue by danielmatthew** [talis/bootstrap-sass#7]
Chrome applies `:focus` state to a button in its down (or active) state which draws an outline around it. This behaviour isn't present in Safari or Firefox - but then, these two browsers are stricter about what controls `:focus` can be applied to by default.

```css
.btn:focus, .btn.focus, .btn:active:focus, .btn:active.focus, .btn.active:focus, .btn.active.focus {
    outline: thin dotted;
    outline: 0;
    box-shadow: 0 0 0 1px #017d87;
}

.btn-group .dropdown-toggle:active, .btn-group.open .dropdown-toggle {
    outline: 0;
}
```
